# Generated by Django 5.0.7 on 2024-08-27 21:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Autor",
            fields=[
                ("id_autor", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "autor",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Categoria",
            fields=[
                ("id_categoria", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "categoria",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Libro",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("titulo", models.CharField(max_length=100)),
                ("fecha", models.IntegerField(default=20240815)),
                ("valoracion", models.IntegerField(default=None)),
            ],
            options={
                "db_table": "libro",
                "managed": False,
            },
        ),
    ]
